# Generated by Django 3.2.5 on 2021-07-22 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0002_remove_candidate_last_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_editor_user', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑者'),
        ),
    ]
