# Generated by Django 3.2.5 on 2021-07-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_candidate_last_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='last_editor',
        ),
    ]
